messages = [
    "Reconstructing your financial crimes...",
    "Parsing your questionable life choices...",
    "Auditing your past optimism...",
    "Calculating how coffee became a lifestyle...",
    "Summoning the ghosts of purchases past...",
    "Replaying your economic decisions in slow motion...",
    "Analyzing where the money went. Again.",
    "Turning denial into data...",
    "Converting impulse into statistics...",
    "Welcome back to the consequences of your own actions.",
    "Initializing fiscal introspection module...",
    "Loading regret-driven analytics engine...",
    "Compiling spending history...",
    "Optimizing your relationship with reality...",
    "Booting budget-awareness daemon...",
    "Mounting financial truth filesystem...",
    "Running post-mortem on your wallet...",
    "Allocating memory for bad decisions...",
    "Indexing transactions you forgot about...",
    "Starting the accountant you never wanted...",
    "Detecting abnormal caffeine-related expenses...",
    "Estimating your lifetime coffee investment...",
    "Identifying recurring café-based happiness...",
    "Normalizing coffee-to-income ratio...",
    "Coffee spending classified as infrastructure...",
    "Auditing your relationship with baristas...",
    "I promise not to judge. Much.",
    "Your money story is safe with me. Probably.",
    "Let's pretend this is all under control.",
    "I see everything. Especially the late-night purchases.",
    "Trust me, I've seen worse.",
    "Preparing polite disappointment...",
    "Simulating financial responsibility...",
    "Let's call this 'data-driven maturity'.",
    "Sharpening virtual pencil...",
    "Straightening virtual glasses...",
    "Summoning inner accountant...",
    "Balancing sheets and expectations...",
    "Dusting off the ledger of truth...",
    "Opening the book of financial honesty...",
    "You spent money. I have proof.",
    "This will hurt a little.",
    "Spoiler: you bought things.",
    "Numbers don't lie. Unfortunately.",
    "Facing the spreadsheet of destiny...",
    "Reality check loading...",
    "Brace yourself for statistics.",
    "Decrypting wallet activity...",
    "Accessing secure regret vault...",
    "Running financial forensics...",
    "Tracing money packets...",
    "Establishing connection to reality...",
    "Root access granted to your expenses...",
    "Scanning for fiscal anomalies...",
    "Breathe in. Breathe out. It's just numbers.",
    "This is a safe space for bad decisions.",
    "Let the data cleanse you...",
    "Acceptance begins with CSV files.",
    "Today we face the numbers peacefully.",
    "Yes, this is still better than Excel.",
    "You could have used a spreadsheet. You didn't.",
    "Good choice building this tool. You clearly needed it.",
    "This app exists for a reason. You know why.",
    "Future you thanks present you.",
    "Past you apologizes silently.",
    "Rolling for financial awareness... d20 → 3",
    "Achievement unlocked: Budget Curiosity",
    "XP gained: +5 Financial Anxiety",
    "Quest started: Track where the gold went",
    "Inventory check: Mostly receipts",
    "NPC accountant has entered the chat"
]